name: Arcade CI
run-name: ${{github.actor}} Arcade CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  EXECUTABLE: "arcade"
  GRAPHICAL_LIBRARY: "arcade_ncurses.so,arcade_sdl2.so,arcade_sfml.so"
  GAME_LIBRARY: "arcade_nibbler.so,arcade_snake.so"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v2

      - name: Check compilation
        run: |
          mkdir ./build && cd ./build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cd ..

      - name: Check binary
        run: |
          if [[ ! -x "./${EXECUTABLE}" ]]; then
          echo "Error: Binary ${EXECUTABLE} not found."
          exit 1
          fi

      - name: Check shared libraries (Graphical libraries)
        run: |
          IFS=',' read -ra ADDR <<< $GRAPHICAL_LIBRARY
          for lib in "${ADDR[@]}"; do
            if [[ ! -e "./lib/${lib}" ]]; then
              echo "Error: Library $lib not found."
              exit 1
            fi
          done

      - name: Check shared libraries (Graphical libraries)
        run: |
          IFS=',' read -ra ADDR <<< $GAME_LIBRARY
          for lib in "${ADDR[@]}"; do
            if [[ ! -e "./lib/${lib}" ]]; then
              echo "Error: Library $lib not found."
              exit 1
            fi
          done
