name: Arcade CI
run-name: ${{github.actor}} Arcade CI
on:
  push:
    branches-ignore:
      - " ga-ignore-"
  pull_request:
    branches-ignore:
      - " ga-ignore-"
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Check update
        run: |
          sudo apt-get update 

      - name: Install CMake
        run: |
          sudo apt-get install -y cmake

      - name: Install dependency
        run: |
          sudo apt-get install libsfml-dev

      - name: Compile project
        run: |
          cmake -DCMAKE_CXX_FLAGS="-Wall -Werror" . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: search executable
        run: |
          ls ./arcade ./lib/ || { echo "Executable arcade not found" && exit 1; }
